[metadata]

date = "09/01/2021"
material_notes = "Standard Quality-Support"

[settings]

support_enable = true
support_interface_enable = true
support_angle = 45
support_infill_rate = 15
support_pattern = "zigzag"
support_type = "buildplate"
layer_height = 0.2
layer_height_0 = 0.2
wall_thickness = 0.8
bottom_layers = 4
initial_bottom_layers = 4
top_layers = 4
z_seam_type = "sharpest_corner"
top_bottom_pattern = "lines"
top_bottom_pattern_0 = "lines"
infill_before_walls = false
infill_sparse_density = 40
infill_pattern = "cubic"
ironing_enabled = true