[metadata]

date = "09/01/2021"
material_notes = "Standard Quality-Support"

[settings]

support_enable = true
support_interface_enable = true
support_angle = 45
support_infill_rate = 15
support_pattern = "zigzag"
support_type = "buildplate"
layer_height = 0.2
layer_height_0 = 0.2
wall_thickness = 0.8
bottom_layers = 4
initial_bottom_layers = 4
top_layers = 4
z_seam_type = "sharpest_corner"
top_bottom_pattern = "lines"
top_bottom_pattern_0 = "lines"
infill_before_walls = false
infill_sparse_density = 40
infill_pattern = "cubic"
ironing_enabled = true
machine_width = 300
machine_depth = 300
machine_height = 350
machine_nozzle_size = 0.4
machine_shape = "rectangular"
machine_center_is_zero = false
machine_heated_bed = true
machine_start_gcode = """ 
;Heating & Temperature Set 
M140 S{material_bed_temperature_layer_0}     ; start bed heating up 
M105 ; Report Temperature 
M190 S{material_bed_temperature_layer_0} ; Wait for Bed Temperature 
M104 S{material_print_temperature_layer_0}   ; set extruder to reach initial printing temp, held back for ooze reasons 
M105 ; Report Temperature 
M109 S{material_print_temperature_layer_0}   ; wait for extruder to reach initial printing temp 
;Custom Gcode Start 
G28 ;Home
G1 Z15.0 F2000 ;Move the platform
""" 
machine_end_gcode = """ 
M104 S0
M140 S0
G92 E0
G1 E-10 F2000
G28 X0 Y0
M84
""" 
machine_gcode_flavor = "RepRap (Marlin/Sprinter)" 
machine_head_with_fans_x_min = -20
machine_head_with_fans_y_min = -10
machine_head_with_fans_x_max = 10
machine_head_with_fans_y_max = 10
gantry_height = 286
