[metadata]

date = "09/01/2021"
material_notes = "SuperQuality-NonSupport"

[settings]

support_enable = false
support_interface_enable = true
support_angle = 45
support_infill_rate = 15
support_pattern = "zigzag"
support_type = "buildplate"
layer_height = 0.12
layer_height_0 = 0.2
wall_thickness = 1.2
bottom_layers = 7
initial_bottom_layers = 7
top_layers = 7
z_seam_type = "sharpest_corner"
top_bottom_pattern = "lines"
top_bottom_pattern_0 = "lines"
infill_before_walls = false
infill_sparse_density = 40
infill_pattern = "cubic"
ironing_enabled = true