[metadata]

date = "09/01/2021"
material_notes = "SuperQuality-Support"

[settings]

support_enable = true
support_interface_enable = true
support_angle = 45
support_infill_rate = 15
support_pattern = "zigzag"
support_type = "buildplate"
layer_height = 0.12
layer_height_0 = 0.2
wall_thickness = 1.2
bottom_layers = 7
initial_bottom_layers = 7
top_layers = 7
z_seam_type = "sharpest_corner"
top_bottom_pattern = "lines"
top_bottom_pattern_0 = "lines"
infill_before_walls = false
infill_sparse_density = 40
infill_pattern = "cubic"
ironing_enabled = true
machine_width = 180
machine_depth = 180
machine_height = 180
machine_nozzle_size = 0.4
machine_shape ="rectangular"
machine_center_is_zero =false
machine_heated_bed =true
machine_start_gcode = """ 
;Custom Gcode Start 
M201 X1250 Y1250 Z400 E5000 ; sets maximum accelerations
M203 X180 Y180 Z12 E80 ; sets maximum feedrates
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits
M221 S100 ; reset flow
G90 ; use absolute positioning
M82 ; absolute extrusion mode
M104 S170 ; set extruder temp for bed leveling
M140 S{material_bed_temperature_layer_0} ; set bed temp
M109 R170 ; wait for extruder temp
M190 S{material_bed_temperature_layer_0} ; wait for bed temp
G28 ; home all
G29 ; mesh bed leveling
M104 S{material_print_temperature_layer_0} ; set extruder temp
G92 E0.0
G1 Y-2 X179 F2400
G1 Z3 F720
M109 S{material_print_temperature_layer_0} ; wait for extruder temp
G92 E0.0
G1 X170 F1000
G1 Z0.2 F720
G1 X110 E8 F900
G1 X40 E18 F900
G92 E0.0
M900 K0.2 ; LA
""" 
machine_end_gcode = """ 
M104 S0 ; turn off extruder
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 X178 Y180 F4200 ; park print head
M84 ; disable motors
""" 
machine_gcode_flavor = "RepRap (Marlin/Sprinter)"
machine_head_with_fans_x_min =  -31
machine_head_with_fans_y_min = -40
machine_head_with_fans_x_max = 34
machine_head_with_fans_y_max = 31
gantry_height = 286
