[metadata]

date = "09/01/2021"
material_notes = "Standard Quality-Support"

[settings]

support_enable = true
support_interface_enable = true
support_angle = 45
support_infill_rate = 15
support_pattern = "zigzag"
support_type = "buildplate"
layer_height = 0.2
layer_height_0 = 0.2
wall_thickness = 0.8
bottom_layers = 4
initial_bottom_layers = 4
top_layers = 4
z_seam_type = "sharpest_corner"
top_bottom_pattern = "lines"
top_bottom_pattern_0 = "lines"
infill_before_walls = false
infill_sparse_density = 40
infill_pattern = "cubic"
ironing_enabled = true
machine_width = 250
machine_depth = 210
machine_height = 200
machine_nozzle_size = 0.4
machine_shape ="rectangular"
machine_center_is_zero =false
machine_heated_bed =true
machine_start_gcode = """ 
;Custom Gcode Start 
G21 ; set units to millimeters
G90 ; use absolute positioning
M82 ; absolute extrusion mode
M104 S{material_print_temperature_layer_0} ; set extruder temp
M140 S{material_bed_temperature_layer_0} ; set bed temp
M190 S{material_bed_temperature_layer_0} ; wait for bed temp
M109 S{material_print_temperature_layer_0} ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G92 E0.0 ; reset extruder distance position
G1 Y-3.0 F1000.0 ; go outside print area
G1 X60.0 E9.0 F1000.0 ; intro line
G1 X100.0 E21.5 F1000.0 ; intro line
G92 E0.0 ; reset extruder distance position
""" 
machine_end_gcode = """ 
M104 S0 ; turn off extruder
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 X0 Y210; home X axis and push Y forward
M84 ; disable motors
""" 
machine_gcode_flavor = "RepRap (Marlin/Sprinter)"
machine_head_with_fans_x_min =  -31
machine_head_with_fans_y_min = -40
machine_head_with_fans_x_max = 34
machine_head_with_fans_y_max = 31
gantry_height = 286
