# This file maps profile filenames (excluding .toml)
# to names as it appears in the UI drop down menus

[machine_profiles]

aneta6	=	"Anet A6"
aneta8	=	"Anet A8"
aneta8plus	=	"Anet A8 Plus"
anetet4	=	"Anet ET4"
anetet4pro	=	"Anet ET4 Pro"
anetet4x	=	"Anet ET4X"
anetet5	=	"Anet ET5"
anetet5x	=	"Anet ET5X"
crealitycr10	=	"Creality CR-10"
crealitycr10max	=	"Creality CR10 Max"
crealitycr10mini	=	"Creality CR10 Mini"
crealitycr10s	=	"Creality CR10s"
crealitycr10spro	=	"Creality CR10s Pro"
crealityender3	=	"Creality Ender 3"
crealityenderpro	=	"Creality Ender 3 Pro"
crealityender3v2	=	"Creality Ender 3 V2"
crealityender5	=	"Creality Ender 5"
crealityender5plus	=	"Creality Ender 5 Plus"
crealitycr20	=	"Creality CR-20"
crealitycr20pro	=	"Creality CR-20 Pro"
crealitycrx	=	"Creality CR-X"
crealitycr6se	=	"Creality CR-6SE"
prusamini	=	"Original Prusa Mini"
prusai3mk2	=	"Original Prusai 3MK2.5S/MK2.5/MK2S"
prusai3mk3	=	"Original Prusai 3MK3S/MK3"
artilerrygenius	=	"Artilerry Genius"
artilerrysidewinder	=	"Artilerry Sidewinder X1"


[print_profiles]

plaauguth = "PLA auguth"
absauguth = "ABS auguth"
petgauguth = "PETG auguth"
tpu95auguth = "TPU95 auguth"
nylonauguth = "Nylon auguth"
