# This file maps profile filenames (excluding .toml)
# to names as it appears in the UI drop down menus

[machine_profiles]

aneta6supersupport	 = 	"Anet A6 Super Quality - Support"
aneta8supersupport	 = 	"Anet A8 Super Quality - Support"
aneta8plussupersupport	 = 	"Anet A8 Plus Super Quality - Support"
anetet4supersupport	 = 	"Anet ET4 Super Quality - Support"
anetet4prosupersupport	 = 	"Anet ET4 Pro Super Quality - Support"
anetet4xsupersupport	 = 	"Anet ET4X Super Quality - Support"
anetet5supersupport	 = 	"Anet ET5 Super Quality - Support"
anetet5xsupersupport	 = 	"Anet ET5X Super Quality - Support"
crealitycr10supersupport	 = 	"Creality CR-10 Super Quality - Support"
crealitycr10maxsupersupport	 = 	"Creality CR10Max Super Quality - Support"
crealitycr10minisupersupport	 = 	"Creality CR10 Mini Super Quality - Support"
crealitycr10ssupersupport	 = 	"Creality CR10s Super Quality - Support"
crealitycr10sprosupersupport	 = 	"Creality CR10s Pro Super Quality - Support"
crealityender3supersupport	 = 	"Creality Ender 3 Super Quality - Support"
crealityenderprosupersupport	 = 	"Creality Ender 3 Pro Super Quality - Support"
crealityender3v2supersupport	 = 	"Creality Ender 3 V2 Super Quality - Support"
crealityender5supersupport	 = 	"Creality Ender 5 Super Quality - Support"
crealityender5plussupersupport	 = 	"Creality Ender 5 Plus Super Quality - Support"
crealitycr20supersupport	 = 	"Creality CR-20 Super Quality - Support"
crealitycr20prosupersupport	 = 	"Creality CR-20 Pro Super Quality - Support"
crealitycrxsupersupport	 = 	"Creality CR-X Super Quality - Support"
crealitycr6sesupersupport	 = 	"Creality CR-6 SE Super Quality - Support"
prusaminisupersupport	 = 	"Original Prusa Mini Super Quality - Support"
prusai3mk2supersupport	 = 	"Original Prusa i3 MK2.5S/MK2.5/MK2S Super Quality - Support"
prusai3mk3supersupport	 = 	"Original Prusa i3 MK3S/MK3 Super Quality - Support"
artilerrygeniussupersupport	 = 	"Artilerry Genius Super Quality - Support"
artilerrysidewindersupersupport	 = 	"Artilerry Sidewinder X1 Super Quality - Support"
aneta6supernonsupport	 = 	"Anet A6 Super Quality - Non Support"
aneta8supernonsupport	 = 	"Anet A8 Super Quality - Non Support"
aneta8plussupernonsupport	 = 	"Anet A8 Plus Super Quality - Non Support"
anetet4supernonsupport	 = 	"Anet ET4 Super Quality - Non Support"
anetet4prosupernonsupport	 = 	"Anet ET4 Pro Super Quality - Non Support"
anetet4xsupernonsupport	 = 	"Anet ET4X Super Quality - Non Support"
anetet5supernonsupport	 = 	"Anet ET5 Super Quality - Non Support"
anetet5xsupernonsupport	 = 	"Anet ET5X Super Quality - Non Support"
crealitycr10supernonsupport	 = 	"Creality CR-10 Super Quality - Non Support"
crealitycr10maxsupernonsupport	 = 	"Creality CR10Max Super Quality - Non Support"
crealitycr10minisupernonsupport	 = 	"Creality CR10 Mini Super Quality - Non Support"
crealitycr10ssupernonsupport	 = 	"Creality CR10s Super Quality - Non Support"
crealitycr10sprosupernonsupport	 = 	"Creality CR10s Pro Super Quality - Non Support"
crealityender3supernonsupport	 = 	"Creality Ender 3 Super Quality - Non Support"
crealityenderprosupernonsupport	 = 	"Creality Ender 3 Pro Super Quality - Non Support"
crealityender3v2supernonsupport	 = 	"Creality Ender 3 V2 Super Quality - Non Support"
crealityender5supernonsupport	 = 	"Creality Ender 5 Super Quality - Non Support"
crealityender5plussupernonsupport	 = 	"Creality Ender 5 Plus Super Quality - Non Support"
crealitycr20supernonsupport	 = 	"Creality CR-20 Super Quality - Non Support"
crealitycr20prosupernonsupport	 = 	"Creality CR-20 Pro Super Quality - Non Support"
crealitycrxsupernonsupport	 = 	"Creality CR-X Super Quality - Non Support"
crealitycr6sesupernonsupport	 = 	"Creality CR-6 SE Super Quality - Non Support"
prusaminisupernonsupport	 = 	"Original Prusa Mini Super Quality - Non Support"
prusai3mk2supernonsupport	 = 	"Original Prusa i3 MK2.5S/MK2.5/MK2S Super Quality - Non Support"
prusai3mk3supernonsupport	 = 	"Original Prusa i3 MK3S/MK3 Super Quality - Non Support"
artilerrygeniussupernonsupport	 = 	"Artilerry Genius Super Quality - Non Support"
artilerrysidewindersupernonsupport	 = 	"Artilerry Sidewinder X1 Super Quality - Non Support"
aneta6dynamicsupport	 = 	"Anet A6 Dynamic Quality - Support"
aneta8dynamicsupport	 = 	"Anet A8 Dynamic Quality - Support"
aneta8plusdynamicsupport	 = 	"Anet A8 Plus Dynamic Quality - Support"
anetet4dynamicsupport	 = 	"Anet ET4 Dynamic Quality - Support"
anetet4prodynamicsupport	 = 	"Anet ET4 Pro Dynamic Quality - Support"
anetet4xdynamicsupport	 = 	"Anet ET4X Dynamic Quality - Support"
anetet5dynamicsupport	 = 	"Anet ET5 Dynamic Quality - Support"
anetet5xdynamicsupport	 = 	"Anet ET5X Dynamic Quality - Support"
crealitycr10dynamicsupport	 = 	"Creality CR-10 Dynamic Quality - Support"
crealitycr10maxdynamicsupport	 = 	"Creality CR10Max Dynamic Quality - Support"
crealitycr10minidynamicsupport	 = 	"Creality CR10 Mini Dynamic Quality - Support"
crealitycr10sdynamicsupport	 = 	"Creality CR10s Dynamic Quality - Support"
crealitycr10sprodynamicsupport	 = 	"Creality CR10s Pro Dynamic Quality - Support"
crealityender3dynamicsupport	 = 	"Creality Ender 3 Dynamic Quality - Support"
crealityenderprodynamicsupport	 = 	"Creality Ender 3 Pro Dynamic Quality - Support"
crealityender3v2dynamicsupport	 = 	"Creality Ender 3 V2 Dynamic Quality - Support"
crealityender5dynamicsupport	 = 	"Creality Ender 5 Dynamic Quality - Support"
crealityender5plusdynamicsupport	 = 	"Creality Ender 5 Plus Dynamic Quality - Support"
crealitycr20dynamicsupport	 = 	"Creality CR-20 Dynamic Quality - Support"
crealitycr20prodynamicsupport	 = 	"Creality CR-20 Pro Dynamic Quality - Support"
crealitycrxdynamicsupport	 = 	"Creality CR-X Dynamic Quality - Support"
crealitycr6sedynamicsupport	 = 	"Creality CR-6 SE Dynamic Quality - Support"
prusaminidynamicsupport	 = 	"Original Prusa Mini Dynamic Quality - Support"
prusai3mk2dynamicsupport	 = 	"Original Prusa i3 MK2.5S/MK2.5/MK2S Dynamic Quality - Support"
prusai3mk3dynamicsupport	 = 	"Original Prusa i3 MK3S/MK3 Dynamic Quality - Support"
artilerrygeniusdynamicsupport	 = 	"Artilerry Genius Dynamic Quality - Support"
artilerrysidewinderdynamicsupport	 = 	"Artilerry Sidewinder X1 Dynamic Quality - Support"
aneta6dynamicnonsupport	 = 	"Anet A6 Dynamic Quality - Non Support"
aneta8dynamicnonsupport	 = 	"Anet A8 Dynamic Quality - Non Support"
aneta8plusdynamicnonsupport	 = 	"Anet A8 Plus Dynamic Quality - Non Support"
anetet4dynamicnonsupport	 = 	"Anet ET4 Dynamic Quality - Non Support"
anetet4prodynamicnonsupport	 = 	"Anet ET4 Pro Dynamic Quality - Non Support"
anetet4xdynamicnonsupport	 = 	"Anet ET4X Dynamic Quality - Non Support"
anetet5dynamicnonsupport	 = 	"Anet ET5 Dynamic Quality - Non Support"
anetet5xdynamicnonsupport	 = 	"Anet ET5X Dynamic Quality - Non Support"
crealitycr10dynamicnonsupport	 = 	"Creality CR-10 Dynamic Quality - Non Support"
crealitycr10maxdynamicnonsupport	 = 	"Creality CR10Max Dynamic Quality - Non Support"
crealitycr10minidynamicnonsupport	 = 	"Creality CR10 Mini Dynamic Quality - Non Support"
crealitycr10sdynamicnonsupport	 = 	"Creality CR10s Dynamic Quality - Non Support"
crealitycr10sprodynamicnonsupport	 = 	"Creality CR10s Pro Dynamic Quality - Non Support"
crealityender3dynamicnonsupport	 = 	"Creality Ender 3 Dynamic Quality - Non Support"
crealityenderprodynamicnonsupport	 = 	"Creality Ender 3 Pro Dynamic Quality - Non Support"
crealityender3v2dynamicnonsupport	 = 	"Creality Ender 3 V2 Dynamic Quality - Non Support"
crealityender5dynamicnonsupport	 = 	"Creality Ender 5 Dynamic Quality - Non Support"
crealityender5plusdynamicnonsupport	 = 	"Creality Ender 5 Plus Dynamic Quality - Non Support"
crealitycr20dynamicnonsupport	 = 	"Creality CR-20 Dynamic Quality - Non Support"
crealitycr20prodynamicnonsupport	 = 	"Creality CR-20 Pro Dynamic Quality - Non Support"
crealitycrxdynamicnonsupport	 = 	"Creality CR-X Dynamic Quality - Non Support"
crealitycr6sedynamicnonsupport	 = 	"Creality CR-6 SE Dynamic Quality - Non Support"
prusaminidynamicnonsupport	 = 	"Original Prusa Mini Dynamic Quality - Non Support"
prusai3mk2dynamicnonsupport	 = 	"Original Prusa i3 MK2.5S/MK2.5/MK2S Dynamic Quality - Non Support"
prusai3mk3dynamicnonsupport	 = 	"Original Prusa i3 MK3S/MK3 Dynamic Quality - Non Support"
artilerrygeniusdynamicnonsupport	 = 	"Artilerry Genius Dynamic Quality - Non Support"
artilerrysidewinderdynamicnonsupport	 = 	"Artilerry Sidewinder X1 Dynamic Quality - Non Support"
aneta6standardsupport	 = 	"Anet A6 Standard Quality - Support"
aneta8standardsupport	 = 	"Anet A8 Standard Quality - Support"
aneta8plusstandardsupport	 = 	"Anet A8 Plus Standard Quality - Support"
anetet4standardsupport	 = 	"Anet ET4 Standard Quality - Support"
anetet4prostandardsupport	 = 	"Anet ET4 Pro Standard Quality - Support"
anetet4xstandardsupport	 = 	"Anet ET4X Standard Quality - Support"
anetet5standardsupport	 = 	"Anet ET5 Standard Quality - Support"
anetet5xstandardsupport	 = 	"Anet ET5X Standard Quality - Support"
crealitycr10standardsupport	 = 	"Creality CR-10 Standard Quality - Support"
crealitycr10maxstandardsupport	 = 	"Creality CR10Max Standard Quality - Support"
crealitycr10ministandardsupport	 = 	"Creality CR10 Mini Standard Quality - Support"
crealitycr10sstandardsupport	 = 	"Creality CR10s Standard Quality - Support"
crealitycr10sprostandardsupport	 = 	"Creality CR10s Pro Standard Quality - Support"
crealityender3standardsupport	 = 	"Creality Ender 3 Standard Quality - Support"
crealityenderprostandardsupport	 = 	"Creality Ender 3 Pro Standard Quality - Support"
crealityender3v2standardsupport	 = 	"Creality Ender 3 V2 Standard Quality - Support"
crealityender5standardsupport	 = 	"Creality Ender 5 Standard Quality - Support"
crealityender5plusstandardsupport	 = 	"Creality Ender 5 Plus Standard Quality - Support"
crealitycr20standardsupport	 = 	"Creality CR-20 Standard Quality - Support"
crealitycr20prostandardsupport	 = 	"Creality CR-20 Pro Standard Quality - Support"
crealitycrxstandardsupport	 = 	"Creality CR-X Standard Quality - Support"
crealitycr6sestandardsupport	 = 	"Creality CR-6 SE Standard Quality - Support"
prusaministandardsupport	 = 	"Original Prusa Mini Standard Quality - Support"
prusai3mk2standardsupport	 = 	"Original Prusa i3 MK2.5S/MK2.5/MK2S Standard Quality - Support"
prusai3mk3standardsupport	 = 	"Original Prusa i3 MK3S/MK3 Standard Quality - Support"
artilerrygeniusstandardsupport	 = 	"Artilerry Genius Standard Quality - Support"
artilerrysidewinderstandardsupport	 = 	"Artilerry Sidewinder X1 Standard Quality - Support"
aneta6standardnonsupport	 = 	"Anet A6 Standard Quality - Non Support"
aneta8standardnonsupport	 = 	"Anet A8 Standard Quality - Non Support"
aneta8plusstandardnonsupport	 = 	"Anet A8 Plus Standard Quality - Non Support"
anetet4standardnonsupport	 = 	"Anet ET4 Standard Quality - Non Support"
anetet4prostandardnonsupport	 = 	"Anet ET4 Pro Standard Quality - Non Support"
anetet4xstandardnonsupport	 = 	"Anet ET4X Standard Quality - Non Support"
anetet5standardnonsupport	 = 	"Anet ET5 Standard Quality - Non Support"
anetet5xstandardnonsupport	 = 	"Anet ET5X Standard Quality - Non Support"
crealitycr10standardnonsupport	 = 	"Creality CR-10 Standard Quality - Non Support"
crealitycr10maxstandardnonsupport	 = 	"Creality CR10Max Standard Quality - Non Support"
crealitycr10ministandardnonsupport	 = 	"Creality CR10 Mini Standard Quality - Non Support"
crealitycr10sstandardnonsupport	 = 	"Creality CR10s Standard Quality - Non Support"
crealitycr10sprostandardnonsupport	 = 	"Creality CR10s Pro Standard Quality - Non Support"
crealityender3standardnonsupport	 = 	"Creality Ender 3 Standard Quality - Non Support"
crealityenderprostandardnonsupport	 = 	"Creality Ender 3 Pro Standard Quality - Non Support"
crealityender3v2standardnonsupport	 = 	"Creality Ender 3 V2 Standard Quality - Non Support"
crealityender5standardnonsupport	 = 	"Creality Ender 5 Standard Quality - Non Support"
crealityender5plusstandardnonsupport	 = 	"Creality Ender 5 Plus Standard Quality - Non Support"
crealitycr20standardnonsupport	 = 	"Creality CR-20 Standard Quality - Non Support"
crealitycr20prostandardnonsupport	 = 	"Creality CR-20 Pro Standard Quality - Non Support"
crealitycrxstandardnonsupport	 = 	"Creality CR-X Standard Quality - Non Support"
crealitycr6sestandardnonsupport	 = 	"Creality CR-6 SE Standard Quality - Non Support"
prusaministandardnonsupport	 = 	"Original Prusa Mini Standard Quality - Non Support"
prusai3mk2standardnonsupport	 = 	"Original Prusa i3 MK2.5S/MK2.5/MK2S Standard Quality - Non Support"
prusai3mk3standardnonsupport	 = 	"Original Prusa i3 MK3S/MK3 Standard Quality - Non Support"
artilerrygeniusstandardnonsupport	 = 	"Artilerry Genius Standard Quality - Non Support"
artilerrysidewinderstandardnonsupport	 = 	"Artilerry Sidewinder X1 Standard Quality - Non Support"

[print_profiles]

plaauguth = "PLA auguth"
absauguth = "ABS auguth"
petgauguth = "PETG auguth"
tpu95auguth = "TPU95 auguth"
nylonauguth = "Nylon auguth"
