[metadata]

date = "09/01/2021"
material_notes = "TPU Material for auguth Devices"

[settings]

material_diameter = 1.75
material_flow = 100
material_bed_temperature = 0
material_print_temperature = 228
material_keep_part_removal_temperature = false
material_part_removal_temperature = false
material_wipe_temperature = false
retraction_enable = true
retraction_amount = 6.5
retraction_combing = "off"
retraction_speed = 25
cool_fan_enabled = true
cool_fan_speed= 100
cool_fan_speed_max = 100
cool_fan_speed_min = 100